[alembic]
# Path to migration scripts
script_location = app/db/migrations

# sys.path path, prepended to sys.path if present.
prepend_sys_path = .

# Version locations
version_locations = app/db/migrations/versions

# Set to 'true' to run the environment during the 'revision' command
# run_name = alembic

# Logging configuration
[loggers]
keys = root,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
