import React, { useEffect, useState } from 'react';
import { CalendarDays, CheckCircle2, KeyRound, Users } from 'lucide-react';
import { getPublishedEvents, joinEvent } from '../../services/events';
import { TrainingEvent } from '../../types/event';
import { useAuth } from '../../hooks/useAuth';

interface Props { onOpen: (eventId: string) => void; }

export const StudentEventsPage: React.FC<Props> = ({ onOpen }) => {
  const { user } = useAuth(); const [events, setEvents] = useState<TrainingEvent[]>([]); const [code, setCode] = useState(''); const [notice, setNotice] = useState<string | null>(null);
  const refresh = () => user && getPublishedEvents().then(setEvents);
  useEffect(() => { void refresh(); }, [user]);
  const join = async (submittedCode?: string) => { if (!user) return; try { const event = await joinEvent(submittedCode || code); setCode(''); setNotice(`You joined ${event.title}.`); refresh(); } catch (err: any) { setNotice(err.message); } };
  const mine = events.filter((event) => event.is_enrolled); const available = events.filter((event) => !event.is_enrolled);
  const cards = (items: TrainingEvent[], empty: string) => items.length ? <div className="grid md:grid-cols-2 gap-5">{items.map((event) => <div key={event.id} className="bg-[#0d1322] border border-slate-800 rounded-xl p-5 space-y-4"><div className="flex justify-between gap-3"><div><h2 className="font-bold text-white">{event.title}</h2><p className="mt-1 text-xs text-slate-400 line-clamp-2">{event.description || 'Instructor-led cybersecurity training event.'}</p></div>{event.is_enrolled && <CheckCircle2 className="w-5 h-5 text-emerald-400 flex-shrink-0" />}</div><div className="flex justify-between text-[11px] text-slate-400 font-mono"><span className="flex gap-1 items-center"><CalendarDays className="w-3.5 h-3.5" />{new Date(event.starts_at).toLocaleDateString()}</span><span className="flex gap-1 items-center"><Users className="w-3.5 h-3.5" />{event.enrollment_count}{event.capacity ? `/${event.capacity}` : ''}</span><span>{event.labs.length} labs</span></div>{event.is_enrolled ? <button onClick={() => onOpen(event.id)} className="w-full py-2.5 rounded-lg bg-cyan-500/10 border border-cyan-500/30 text-cyan-400 text-xs font-semibold">Open event</button> : <button onClick={() => join(event.join_code)} className="w-full py-2.5 rounded-lg bg-purple-500/10 border border-purple-500/30 text-purple-300 text-xs font-semibold">Join this event</button>}</div>)}</div> : <div className="py-10 rounded-xl border border-slate-800 bg-[#0d1322] text-center text-slate-500 text-sm">{empty}</div>;
  return <div className="page-enter space-y-8"><div className="border-b border-slate-800 pb-4"><h1 className="text-2xl font-bold text-white">Training Events</h1><p className="text-xs text-slate-400 mt-1">Join an instructor-configured cohort to access its selected labs.</p></div><form onSubmit={(e) => { e.preventDefault(); join(); }} className="surface-card bg-[#0d1322] border border-slate-800 rounded-xl p-5 flex flex-col sm:flex-row gap-3"><div className="flex-1"><label className="text-xs text-slate-300 flex gap-2 items-center mb-2"><KeyRound className="w-4 h-4 text-purple-400" />Have a join code?</label><input value={code} onChange={(e) => setCode(e.target.value.toUpperCase())} className="w-full input-event font-mono" placeholder="Enter code, for example WEB-2026" /></div><button className="sm:self-end px-5 py-2.5 bg-purple-500 text-slate-950 text-xs font-bold rounded">Join event</button></form>{notice && <div className="p-3 rounded bg-slate-800 border border-slate-700 text-xs text-slate-200 flex justify-between"><span>{notice}</span><button onClick={() => setNotice(null)}>×</button></div>}<section><h2 className="text-base font-bold text-white mb-4">My events</h2>{cards(mine, 'You have not joined an event yet. Enter a join code or select an open event below.')}</section><section><h2 className="text-base font-bold text-white mb-4">Open events</h2>{cards(available, 'No events are currently open for enrolment.')}</section></div>;
};
