"""Add PvP fields and SimulationSessionUser

Revision ID: 09d5ee5e26c1
Revises: '005_add_browser_simulations'
Create Date: 2026-09-13 18:53:45.247553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09d5ee5e26c1'
down_revision: Union[str, None] = '005_add_browser_simulations'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_session_users',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('team', sa.Enum('RED', 'BLUE', 'OBSERVER', name='simulationteam'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['simulation_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'user_id')
    )
    op.drop_index(op.f('ix_lab_instances_lab_id'), table_name='lab_instances')
    op.drop_index(op.f('ix_lab_instances_student_id'), table_name='lab_instances')
    op.drop_table('lab_instances')
    op.add_column('simulation_sessions', sa.Column('is_pvp', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('simulation_sessions', sa.Column('join_code', sa.String(length=20), nullable=True))
    op.add_column('simulation_sessions', sa.Column('time_limit_minutes', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_simulation_sessions_join_code'), 'simulation_sessions', ['join_code'], unique=True)
    op.drop_constraint(op.f('training_events_join_code_key'), 'training_events', type_='unique')
    op.drop_index(op.f('ix_training_events_join_code'), table_name='training_events')
    op.create_index(op.f('ix_training_events_join_code'), 'training_events', ['join_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_events_join_code'), table_name='training_events')
    op.create_index(op.f('ix_training_events_join_code'), 'training_events', ['join_code'], unique=False)
    op.create_unique_constraint(op.f('training_events_join_code_key'), 'training_events', ['join_code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_simulation_sessions_join_code'), table_name='simulation_sessions')
    op.drop_column('simulation_sessions', 'time_limit_minutes')
    op.drop_column('simulation_sessions', 'join_code')
    op.drop_column('simulation_sessions', 'is_pvp')
    op.create_table('lab_instances',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('lab_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PROVISIONING', 'RUNNING', 'STOPPED', 'FAILED', name='labinstancestatus'), autoincrement=False, nullable=False),
    sa.Column('container_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('network_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('stopped_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('failure_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], name=op.f('lab_instances_lab_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('lab_instances_student_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lab_instances_pkey')),
    sa.UniqueConstraint('container_id', name=op.f('lab_instances_container_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('network_name', name=op.f('lab_instances_network_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_lab_instances_student_id'), 'lab_instances', ['student_id'], unique=False)
    op.create_index(op.f('ix_lab_instances_lab_id'), 'lab_instances', ['lab_id'], unique=False)
    op.drop_table('simulation_session_users')
    # ### end Alembic commands ###
