import React, { useEffect, useState } from 'react';
import { ArrowLeft, Loader2, Save } from 'lucide-react';
import { getStudentCatalogApi } from '../../services/lab';
import { getEvent, saveEvent } from '../../services/events';
import { LabStudentView } from '../../types/lab';
import { useAuth } from '../../hooks/useAuth';

interface Props { eventId?: string; onBack: () => void; }
const localDate = (value?: string) => value ? new Date(value).toISOString().slice(0, 16) : '';

export const InstructorEventEditorPage: React.FC<Props> = ({ eventId, onBack }) => {
  const { user } = useAuth(); const editing = !!eventId;
  const [labs, setLabs] = useState<LabStudentView[]>([]); const [chosen, setChosen] = useState<string[]>([]);
  const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [joinCode, setJoinCode] = useState('');
  const [startsAt, setStartsAt] = useState(''); const [endsAt, setEndsAt] = useState(''); const [capacity, setCapacity] = useState('');
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { (async () => { try {
    const catalog = await getStudentCatalogApi(); setLabs(catalog);
    if (eventId) { const event = await getEvent(eventId); setTitle(event.title); setDescription(event.description); setJoinCode(event.join_code); setStartsAt(localDate(event.starts_at)); setEndsAt(localDate(event.ends_at)); setCapacity(event.capacity?.toString() || ''); setChosen(event.labs.map((lab) => lab.id)); }
  } catch (err: any) { setError(err.message || 'Unable to load event editor.'); } finally { setLoading(false); } })(); }, [eventId, user?.id]);
  const submit = async (e: React.FormEvent) => { e.preventDefault(); if (!user) return; if (!title.trim() || !joinCode.trim() || !startsAt || !endsAt) return setError('Title, join code, start, and end time are required.'); if (new Date(endsAt) <= new Date(startsAt)) return setError('The event end time must be after its start time.'); if (chosen.length === 0) return setError('Select at least one published lab.'); setSaving(true); setError(null); try { await saveEvent({ title, description, join_code: joinCode, starts_at: new Date(startsAt).toISOString(), ends_at: new Date(endsAt).toISOString(), capacity: capacity ? Number(capacity) : undefined, lab_ids: chosen }, eventId); onBack(); } catch (err: any) { setError(err.message); } finally { setSaving(false); } };
  if (loading) return <div className="min-h-[45vh] flex items-center justify-center text-slate-400"><Loader2 className="w-7 h-7 animate-spin mr-2" />Loading event editor…</div>;
  return <div className="max-w-4xl space-y-6"><button onClick={onBack} className="flex items-center gap-2 text-xs text-slate-400 hover:text-purple-400"><ArrowLeft className="w-4 h-4" />Back to Events</button><div><h1 className="text-2xl font-bold text-white">{editing ? 'Edit Training Event' : 'Create Training Event'}</h1><p className="text-xs text-slate-400 mt-1">Students will only see the event once you publish it.</p></div>{error && <div className="p-3 rounded bg-rose-500/10 border border-rose-500/30 text-rose-400 text-xs">{error}</div>}
    <form onSubmit={submit} className="space-y-6"><div className="bg-[#0d1322] border border-slate-800 rounded-xl p-6 grid gap-4"><div><label className="block text-xs text-slate-300 mb-1">Event title *</label><input required value={title} onChange={(e) => setTitle(e.target.value)} className="w-full input-event" placeholder="Fall Web Security Cohort" /></div><div><label className="block text-xs text-slate-300 mb-1">Description</label><textarea value={description} onChange={(e) => setDescription(e.target.value)} className="w-full input-event" rows={3} placeholder="Who this event is for and what they will learn." /></div><div className="grid sm:grid-cols-2 gap-4"><div><label className="block text-xs text-slate-300 mb-1">Join code *</label><input required value={joinCode} onChange={(e) => setJoinCode(e.target.value.toUpperCase())} className="w-full input-event font-mono" placeholder="WEB-2026" /></div><div><label className="block text-xs text-slate-300 mb-1">Capacity (optional)</label><input type="number" min="1" value={capacity} onChange={(e) => setCapacity(e.target.value)} className="w-full input-event" /></div><div><label className="block text-xs text-slate-300 mb-1">Starts *</label><input required type="datetime-local" value={startsAt} onChange={(e) => setStartsAt(e.target.value)} className="w-full input-event" /></div><div><label className="block text-xs text-slate-300 mb-1">Ends *</label><input required type="datetime-local" value={endsAt} onChange={(e) => setEndsAt(e.target.value)} className="w-full input-event" /></div></div></div>
      <div className="bg-[#0d1322] border border-slate-800 rounded-xl p-6"><h2 className="text-base font-bold text-white">Published labs *</h2><p className="text-xs text-slate-400 mt-1 mb-4">Select the labs included in this event.</p><div className="grid sm:grid-cols-2 gap-3">{labs.map((lab) => <label key={lab.id} className="flex gap-3 p-3 rounded-lg bg-slate-900 border border-slate-800 cursor-pointer hover:border-purple-500/50"><input type="checkbox" checked={chosen.includes(lab.id)} onChange={() => setChosen(chosen.includes(lab.id) ? chosen.filter((id) => id !== lab.id) : [...chosen, lab.id])} /><span><span className="block text-sm text-white font-semibold">{lab.title}</span><span className="text-[11px] text-slate-400">{lab.category} · {lab.difficulty}</span></span></label>)}</div>{labs.length === 0 && <p className="text-xs text-amber-400">No published labs are available. Publish a lab blueprint first.</p>}</div>
      <div className="flex justify-end gap-3"><button type="button" onClick={onBack} className="px-4 py-2 text-xs rounded border border-slate-700 text-slate-300">Cancel</button><button disabled={saving} className="px-5 py-2 bg-purple-500 text-slate-950 font-bold text-xs rounded flex gap-2">{saving ? <Loader2 className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />}{editing ? 'Save event' : 'Create draft'}</button></div>
    </form></div>;
};
